
title: Mi Blog
author: Nacho
description: Blog est√°tico en Jekyll para la actividad de Desarrollo de Aplicaciones en Red.
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
